# Numpy

## shape, dtype, size, itemsize

In [96]:
import numpy as np 

In [97]:
skalar = np.array(9j) 
vektor = np.array([8, 2.3, 5, 3])
matrica = np.array([[2, 3], [9, 0], [8, 1], [0, 0]])
tenzor = np.array([[[2, 3, 8], [2, 2, -3]], [[9, 0, -1], [2, -8, 7]]], dtype=np.int8) #int8 je integer predstavljen s 8 bitova. tj to je 1 bajt

In [98]:
skalar.shape, vektor.shape, matrica.shape, tenzor.shape 

((), (4,), (4, 2), (2, 2, 3))

In [99]:
#ovaj ispis (4,) je posljedica pytona.. shape skalara je prazan, shape vektora je njegova duljina, shape matrica su dimenzije, shape tenzora je broj matrica, kolko svaka ima redaka i broj stupaca.--

In [100]:
np.array([[skalar.size, vektor.size, matrica.size, tenzor.size], 
          [skalar.itemsize, vektor.itemsize, matrica.itemsize, tenzor.itemsize]])

array([[ 1,  4,  8, 12],
       [16,  8,  8,  1]])

In [101]:
tenzor

array([[[ 2,  3,  8],
        [ 2,  2, -3]],

       [[ 9,  0, -1],
        [ 2, -8,  7]]], dtype=int8)

In [102]:
tenzor.reshape(3, 4) #mozemo interpretirati kao matricu 3*4 (1 dio memorije mozemo interpretirati na vise nacina)

array([[ 2,  3,  8,  2],
       [ 2, -3,  9,  0],
       [-1,  2, -8,  7]], dtype=int8)

In [103]:
skalar.dtype, vektor.dtype, matrica.dtype, tenzor.dtype

(dtype('complex128'), dtype('float64'), dtype('int64'), dtype('int8'))

In [104]:
np.array([True, True, False]).dtype, np.array([chr, ord]) #array istina i lazi, dobivamo bool dtype

(dtype('bool'),
 array([<built-in function chr>, <built-in function ord>], dtype=object))

## arange, linspace

In [105]:
np.arange(3, 5.2, 0.1) #daj mi sve brojeve od 3 do 5.2 s korakom 0.1

array([3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2,
       4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1])

In [106]:
np.arange(5, 0, -1, dtype=np.float16) #mozemo mu zadati dtype// arange je isto ko array samo mu mozemo poslati bilo koji tip podataka

array([5., 4., 3., 2., 1.], dtype=float16)

In [107]:
np.linspace(1.41, 2.72) #defaultna vrijednost podjele grafova je 50 dijelova... od 1.41 do 2.72 tako da su razmaci cca ekvidistantni

array([1.41      , 1.43673469, 1.46346939, 1.49020408, 1.51693878,
       1.54367347, 1.57040816, 1.59714286, 1.62387755, 1.65061224,
       1.67734694, 1.70408163, 1.73081633, 1.75755102, 1.78428571,
       1.81102041, 1.8377551 , 1.8644898 , 1.89122449, 1.91795918,
       1.94469388, 1.97142857, 1.99816327, 2.02489796, 2.05163265,
       2.07836735, 2.10510204, 2.13183673, 2.15857143, 2.18530612,
       2.21204082, 2.23877551, 2.2655102 , 2.2922449 , 2.31897959,
       2.34571429, 2.37244898, 2.39918367, 2.42591837, 2.45265306,
       2.47938776, 2.50612245, 2.53285714, 2.55959184, 2.58632653,
       2.61306122, 2.63979592, 2.66653061, 2.69326531, 2.72      ])

In [108]:
np.linspace(0, 100, 8, dtype=int)

array([  0,  14,  28,  42,  57,  71,  85, 100])

In [109]:
np.geomspace(1, 128 # kao linspace ali umjesto aritmetickog niza gleda geometrijski niz.. svaka 7 vrijednost je cijela a ostale se interpoliraju

SyntaxError: unexpected EOF while parsing (<ipython-input-109-90bfff9dd405>, line 1)

## Slučajni brojevi

In [ ]:
np.random.uniform(-1, 1, (3, 5))  # uniformna distribucija na [-1,1> ..trci argument je oblik(shape) u kojem ispisuje.. tu je to matrica 3*5

In [ ]:
np.random.normal(100, 15, 20)  # 20 ljudi sa slučajno odabranim IQ.. standarna devijacija je 15..100 je srednja vrijednost,. a 20 je vektor jednodimenzionalni

In [ ]:
poason = np.random.poisson(50, 1000) #np.mean - srednja vrijednost ... np.std - standarna devijacija
np.mean(poason), np.std(poason, ddof=1) ** 2

## Još malo o matricama


In [ ]:
{k: np.diag([   #np.diag omogucuje da ekstrahira dijagonale matrice,.  
    [1, 5, 7, 2],
    [3, 2, 0, 1],
    [2, 7, 1, 4]
], k) for k in range(-3, 5)}

In [ ]:
np.diag([2, 3, 8], -2) # ili moze konstruirati dijagonalu (ne mora biti glavna)

In [ ]:
np.diag([2,3,6,8])

In [ ]:
np.zeros((2, 9))

In [ ]:
np.ones((2, 9))

In [ ]:
np.eye(3)

In [ ]:
np.array([2,3,6]) + np.eye(3) #stvari se zbrajaju po točkama.. (2,3,6) se zbraja s svakim retkom posebno iz jedinicne matrice

## Datoteke

In [ ]:
temperature = np.genfromtxt('tpt-world.csv', skip_header=1, delimiter=',') #skip_header-koliko prvih redaka preskace
temperature.shape

In [ ]:
godine, podaci = temperature.T #.T transponira matricu

In [ ]:
godine

In [ ]:
podaci.min(), godine.max()

In [ ]:
godine.mean(), podaci.mean(), temperature.mean(), temperature.mean(axis=0) #podaci.mean nam daje srednju vrijednost svih podataka( i godina i temperatura)...najcesce trebamo srednju vrijednost po stupcima.. za to postavljamo axis=0

In [ ]:
temperature.prod(axis=0) #produkt.. tu je vrijednost produkta prevelika pa se dogodio overflow.. niz i dalje postoji , a vrijednost je kao beskonacna

In [ ]:
tenzor

In [ ]:
tenzor.prod(axis=0) #produkt ovog tenzora po osi 0... za tenzor je prvi broj u deklaraciji broj matrica ( kod matrica prvi broj oznacava broj redaka matrice)

In [ ]:
tenzor.prod(axis=1)

In [ ]:
tenzor.prod(axis=2)

In [ ]:
np.savetxt('matrica.csv', matrica, fmt='%2d')

In [ ]:
!cat matrica.csv

In [ ]:
np.save('matrica.npy', matrica) # binarni format.. brzi za ucitavanje od savetxt.. jer treba prevoditi iz txt u binarno i obratno kod ucitavanja i sejvanja

In [ ]:
(np.load('matrica.npy') == matrica).all()

## Indeksiranje

In [ ]:
vektor

In [ ]:
vektor[0], matrica[2, 1], tenzor[0, 1, 0], skalar[()]

In [ ]:
matrica, matrica[:, 1], matrica[2, :], matrica[2], matrica[2, None], matrica[None, 1] #matrica[2, :] drugi redak, svi stupci... : = sve!... None = dodaj jos jednu dimenziju

In [ ]:
matrica[:, 1] = 3  # sve vrijednosti prvog( broji od nule) stupca postavi na 3

In [ ]:
matrica

In [ ]:
tablica = np.arange(100).reshape(10, 10)
tablica

In [ ]:
tablica[3:-2, 1:8:2] # pocni sa trecim retkom, zavrsi 2 retka prije kraja---- pocni s prvim, zavrsi prije osmog i uzmi svaki drugi

In [ ]:
tablica[:, [2, 6, 1]][[3, 2], :] #uzmi kompletne retke ,ali od stupaca uzmi 2 ,6 i 1... 

In [ ]:
tablica[[3, 2, 8], [2, 6, 1]]

In [ ]:
tenzor < 3

In [ ]:
tenzor[tenzor < 3] # ako indeksiramo tenzor s ovim tenzorom manjim od 3( bool) dobivamo vektor s vrijednostima manjih od 3

In [ ]:
niz = np.random.normal(100, 15, 1_000_000) #1 000 000 kvocijenta inteligencije, srednja vrijednost 100 i 15 standarna devijacija

In [ ]:
niz[(niz > 170) | (niz < 35)]

In [ ]:
np.where(niz > 160) # where vraca indekse gdje se nalaze vrijednosti koje zadovoljavaju uvjet

In [ ]:
matrica

In [ ]:
np.where(matrica > 2, matrica, -9) #tamo gdje je veca od 2 uzmi matricu, tamo gdje nije, uzmi -9

In [ ]:
godine[podaci > 0.1] #u sql-u je to ekvivalentno select nesto where nestodrugo

## Vektorizacija

In [ ]:
%time niz * 3 # ovo radi numericki procesor.. (radi vektorski)

In [ ]:
%time np.array([x * 3 for x in niz]) # ovo radi pyton .. puno sporije

In [ ]:
(niz * niz).sum() # pomnozimo po tockama, dobivamo niz, tj vektor i kad sumiramo imamo skalarni produkt

In [ ]:
niz @ niz #manki je unutarnji produkt.. ako prima 2 matrice dat ce produkt matrica, a ako mu damo vektor i matricu dobit cemo djelovanje vektora na matricu

In [ ]:
A = np.random.normal(0, 1, (256, 64))
B = np.random.normal(0, 1, (64, 128))
v = np.random.normal(0, 1, 128)

In [ ]:
%time (A @ B @ v).shape

In [ ]:
np.kron([[1, 2], [3, 4]], [[5, 6, 7], [8, 9, 10]])

In [ ]:
mc = np.matrix([[1, 1j], [-2j, 3j]])

In [ ]:
mc.T.conj() == mc.H

In [ ]:
mc.imag

In [ ]:
np.angle(mc) #argument kompleksnog broja

## Inverzi

In [ ]:
import numpy.linalg as la

In [ ]:
la.det(mc)

In [ ]:
la.inv(mc)

In [ ]:
mc.I @ mc == np.identity(2) # mc je matric... a .I nam daje inverz.. (.T daje transponiranu)

## Učitavanje s weba

In [ ]:
import urllib.request as rq

In [ ]:
import pathlib
with rq.urlopen('https://raw.githubusercontent.com/jrjohansson/scientific-python-lectures/master/stockholm_td_adj.dat') as url:
    pathlib.Path('Stockholm.dat').write_bytes(url.read()) # procitaj sve bytove iz socketa vezano uz ovaj request i zapisi ga nekam?

In [ ]:
stockholm = np.genfromtxt('Stockholm.dat')

In [ ]:
stockholm.shape

In [ ]:
temperatura = stockholm[:, 3]

In [ ]:
!head Stockholm.dat # prva 3 stupca je datum

In [ ]:
temperatura.mean(), temperatura.std(), temperatura.min(), temperatura.max()

In [ ]:
mjesec = stockholm[:, 1] # izdvojimo sve elemente iz stupca 1 i napravimo set od njih (izbacujemo duplikate)
set(mjesec)

In [ ]:
stockholm[mjesec == 2, 3].mean() #indeksiramo s arrayem, koji odabire sve vrijednosti treceg stupca na kojima je vrijednost prvog stupca jednaka 2.... to je srenja temp u veljači

In [ ]:
po_mjesecima = {m: stockholm[mjesec == m, 3].mean() for m in np.arange(1, 13)} #preslikavanje rednog broja mjeseca u prosjecnu temp u mjesecu

In [ ]:
 po_mjesecima # keys su domena (mjeseci)..values je kodomena(vrijednosti)

In [ ]:
%matplotlib inline

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot(po_mjesecima.keys(), po_mjesecima.values())

In [ ]:
plt.plot([1,2,3,5], [0,2,-1,4])

## Vektorizacija funkcija

In [ ]:
mc2 = mc.copy()
mc2[1, 1] = 7

In [ ]:
np.hstack([mc, mc2])

In [ ]:
np.vstack([mc, mc2])

In [ ]:
def funkcija(x):
    if x < 0: return b'N'
    elif x < 99: return b'M'
    elif x < 150: return b'K'
    else: return b'V'

In [112]:
funkcija(niz)

NameError: name 'niz' is not defined

In [110]:
vektorizirana = np.vectorize(funkcija)

In [111]:
%time vektorizirana(niz)

NameError: name 'niz' is not defined

In [90]:
%time np.array(list(map(funkcija, niz)))

NameError: name 'niz' is not defined

## Zadaci za vježbu

Definirajte $A$ kao $5\times5$ slučajnu matricu čiji elementi su uniformno izabrani iz $[0,1\rangle$. Izvucite matricu $B$ kao $2\times2$ gornji lijevi kut od $A$. Kvadrirajte matricu $B$ te njen kvadrat ubacite umjesto $B$ u gornji lijevi kut od $A$.

Objasnite:

In [ ]:
x = np.linspace(0, 1, 3)
y = 2 * x + 1
z = 4 * x - 4
print(x, y, z)

x = np.linspace(0, 1, 3)
y = x
y *= 2
y += 1
z = x
z *= 4
z -= 4
print(x, y, z)

Vektorizirajte rješenje zadatka s trapeznom formulom iz prethodnog predavanja. Vektorizirana funkcija treba za argumente primati funkciju $f$ i broj $n$, te dva niza $a$ i $b$ iste duljine, te vraćati niz brojeva koji odgovaraju aproksimacijama integrala $\int_{a_i}^{b_i}f(x)\,dx$.

Dana je funkcija $$f(x):=\frac{n}{n+1}\cdot\begin{cases}
\left(\frac12\right)^{1+\frac1n}-\left(\frac12-x\right)^{1+\frac1n},&0\le x\le\frac12\\
\left(\frac12\right)^{1+\frac1n}-\left(x-\frac12\right)^{1+\frac1n},&\frac12<x\le1
\end{cases}.$$
Ovdje je $n\in\langle0,1]$ realan broj. Napišite vektoriziranu funkciju za računanje vrijednosti funkcije $f$ na skupu $m$ ekvidistantnih brojeva između $0$ i $1$.

Neka su $x_1, \dotsc, x_n$ uniformno distribuirani slučajni brojevi između $a$ i $b$. Tada se $\int_a^b f$ može aproksimirati sa $\frac{b-a}{n}\cdot\sum_{i=1}^n f(x_i)$, postupkom koji se obično zove _Monte-Carlo integracija_. Napišite funkciju koja kao ulaz prima $a$, $b$, $f$ te $n$ s podrazumijevanom vrijednošću $1000$, te vraća rezultat Monte-Carlo integracije. Funkcija ne smije koristiti petlje.